title: "Voctrainer"
description: "Певческий тренажер"
theme: jekyll-theme-cayman

kramdown:
  toc_levels: 2..3

# Включите плагины
plugins:
  - jekyll-relative-links
  - jekyll-toc

relative_links:
  enabled: true
  collections: true

# Определите структуру навигации
navigation:
  - title: "Главная"
    url: "/"
  - title: "Партитуры"
    url: "/partitures/"
  - title: "О проекте"
    url: "/about/"
